# Generated by Django 3.0.4 on 2020-03-30 08:35

import blog_service.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('Cover_map', models.ImageField(blank=True, upload_to=blog_service.models.user_directory_path, verbose_name='封面')),
                ('author', models.CharField(max_length=16, verbose_name='作者')),
                ('content', tinymce.models.HTMLField()),
                ('pub', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28, verbose_name='变量名')),
                ('values', models.CharField(max_length=240, verbose_name='内容')),
            ],
            options={
                'verbose_name': '自定义变量',
                'verbose_name_plural': '自定义变量',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.CharField(max_length=240, verbose_name='内容')),
                ('pub', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('floor', models.PositiveIntegerField(default=0, verbose_name='楼层')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_service.Blog', verbose_name='博客')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_service.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(to='blog_service.Tag', verbose_name='标签'),
        ),
    ]
